title: "寶島書庫"
permalink: posts/:year-:month-:day-:title.html
collections:
  books:
  categories:
      output: true
      output_ext: xml
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
  -
    scope:
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      type: "categories"
    values:
      layout: "catalog"
gems:
  - jekyll-avatar
  - jekyll-feed
